const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'http://localhost/',runScripts:'outside-only'}),w=dom.window;w.matchMedia=()=>({matches:false});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};
for(const s of w.document.querySelectorAll('script[src]')){const p=s.getAttribute('src');if(p.startsWith('assets/')&&!['assets/app.js','assets/auth.js'].includes(p)){w.eval(fs.readFileSync(p,'utf8'));if(p.endsWith('content-extra.js'))w.ContentExtras.apply();}}
const A=w.Assessment;let count=0,parts=0;
const server=fs.readFileSync('server.js','utf8'),parseSource=server.slice(server.indexOf('function parseFeedbackJson('),server.indexOf('function localFeedback('));const parse=require('vm').runInNewContext(parseSource+';parseFeedbackJson');assert.equal(parse('{}'),null);assert.equal(parse(JSON.stringify({summary:'Test',taskCriteria:[{label:'Content',score:4,evidence:'Text',revision:'Revise'}]})),null);assert.equal(parse(JSON.stringify({summary:'Test',taskCriteria:[{label:'Content',score:0,evidence:'No reason given',revision:'Add one reason'}]})).taskCriteria[0].score,0);
for(const sub of ['de','en','math'])for(const b of w.Exercises['mini-exam'].listBundles(sub)){count++;assert.ok(b.durationMin>0&&b.durationMin<240);for(const p of b.parts){parts++;assert.ok(A.model(p),'model for '+b.id+' '+(p.q||p.text));if(A.written(p)){const r=A.score(p,'A long response does not mean it is correct.',sub);assert.equal(r.correct,null);assert.equal(r.points,null);assert.equal(r.rubric.length,sub==='math'?8:4);assert.equal(A.totals({results:[r]}).pending,1);}else{const r=A.score(p,null,sub);assert.equal(r.points,0,'empty: '+b.id);assert.equal(r.correct,false);}}}
assert.equal(count,15);assert.equal(A.score({type:'fill',text:'___ ___',answers:[['one'],['two']]},['one','wrong'],'en').points,1);
assert.equal(A.score({type:'match',pairs:[['a','A'],['b','B']]},{L0:'L0',L1:'L0'},'en').points,1);
assert.equal(A.score({type:'error',corrections:[{find:'bad',replace:'good'},{find:'x',replace:'y'}]},['good','wrong'],'en').points,1);
const summary=A.rubric({q:'Summary',topic:'summary'},'en'),argument=A.rubric({q:'Comment on',topic:'comment'},'en');assert.notEqual(summary[1].label,argument[1].label);
w.localStorage.setItem('fhr-auth',JSON.stringify({id:'alice'}));const ak=A.key('x');w.localStorage.setItem('fhr-auth',JSON.stringify({id:'bob'}));assert.notEqual(ak,A.key('x'));w.localStorage.removeItem('fhr-auth');assert.equal(A.key('x'),'fhr-app/draft/x');
const original=w.Store.exportData();assert.throws(()=>w.Store.importData('{"version":2,"profile":null}'));assert.equal(w.Store.exportData(),original);
w.Store.importData(original);assert.equal(w.Store.exportData(),original);
const mount=w.document.querySelector('#page-root');const ex={type:'free',subject:'en',q:'Comment on school uniforms.',topic:'comment',modelAnswer:'A possible argument.'};mount.innerHTML=w.Exercises.free.render(ex);let outcome;w.Exercises.free.bind(mount,ex,v=>outcome=v);const text=mount.querySelector('textarea');text.value='word '.repeat(100);text.dispatchEvent(new w.Event('input'));mount.querySelector('[data-action=check]').click();assert.equal(outcome,null);assert.equal(w.Store.load().stats.totalAttempted,0);assert.equal(w.Store.load().writingAttempts.length,1);assert.ok(mount.querySelector('[data-rubric-form]'));
const form=mount.querySelector('[data-rubric-form]');form.querySelectorAll('select').forEach(x=>x.value='2');form.querySelector('textarea').value='My first paragraph gives a reason. I need to include a counterargument.';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(w.Store.load().writingAttempts[0].results[0].review.scores[0],2);
assert.equal(A.totals(w.Store.load().writingAttempts[0]).points,8);
assert.ok(!w.Exercises.free.renderStructuredFeedback({criteria:{inhalt:{score:5}}},'lokal',ex).includes('/5'));
console.log(`PASS: ${count} exams / ${parts} parts; all models; blank and partial scoring; differentiated rubrics; account isolation; safe import; written response and evidence persistence; no false mastery.`);dom.window.close();
