const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const base=path.resolve(__dirname,'..'),dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'http://localhost/',runScripts:'outside-only'}),w=dom.window;
w.matchMedia=()=>({matches:false});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
for(const tag of w.document.querySelectorAll('script[src]')){const src=tag.getAttribute('src');if(!src.startsWith('assets/')||['assets/app.js','assets/auth.js'].includes(src))continue;w.eval(fs.readFileSync(path.join(base,src),'utf8'));if(src.endsWith('content-extra.js'))w.ContentExtras.apply();}
(async()=>{const mount=w.document.querySelector('#page-root'),before=JSON.stringify(w.Store.load().stats);assert.equal(w.LibraryTopics.length,130);assert.equal(w.LibraryExpansion.length,88);assert.equal(new Set(w.LibraryTopics.map(t=>t[1])).size,130);for(const [s,n] of Object.entries({de:29,en:30,math:45,grafik:26})){await w.Pages.bibliothek(mount,{subject:s});assert.equal(mount.querySelectorAll('.library-topic').length,n);assert.ok(mount.querySelectorAll('.library-category').length>=2);}
for(const a of w.LibraryExpansion){assert.ok(a.sections.map(s=>s.text).join(' ').split(/\s+/).length>=90,a.id);assert.ok(w.PracticeSystem.byId[a.practice],a.id+' practice exists');assert.ok(w.LibraryReadingSources[a.source]);await w.Pages.bibliothek(mount,{ref:a.id,subject:a.subject});assert.equal(mount.querySelectorAll('[data-library-reading] section').length,4);assert.ok(mount.querySelector('[data-theory-practice]'));assert.equal(mount.querySelectorAll('[data-library-reading] input, [data-library-reading] button').length,0);if(a.subject==='en')assert.ok(!/Aufgabe|Lösung|Verstehen|Merken|Selbsteinschätzung/.test(mount.textContent));}
assert.equal(w.DesignProjects.length,16);for(const p of w.DesignProjects){assert.equal(p.format,'project');assert.equal(p.steps.length,5);assert.ok(p.minutes>=300);for(const field of ['Ausgangssituation','Ziel','Zielgruppe','Anforderungen','Ergebnisse','Technische_Vorgaben','Einschränkungen'])assert.ok(p.brief[field]?.length,p.id+' '+field);assert.ok(p.reading.every(id=>w.LibraryExpansion.some(a=>a.id===id)));await w.Pages.praxis(mount,{ref:p.id});assert.equal(mount.querySelectorAll('[data-stage]').length,5);assert.ok(mount.querySelector('[data-design-brief]'));assert.equal(mount.querySelectorAll('[data-deliverable]').length,p.brief.Ergebnisse.length);}
const id='design-ui';for(let i=0;i<3;i++)w.PracticeSystem.finishStage(id,i,'Documented own outcome '+i,'I revised the result using the criteria',2);assert.ok(!w.Store.load().practiceWork[id].completedAt,'three of five is not completion');for(let i=3;i<5;i++)w.PracticeSystem.finishStage(id,i,'Documented outcome '+i,'I checked all planned states',3);assert.ok(w.Store.load().practiceWork[id].completedAt);const plan=w.PracticeSystem.build(w.Store.load(),'2026-10-12');assert.ok(!plan.weeks.flatMap(w=>w.days.flatMap(d=>d.tasks)).some(t=>t.assignmentId===id),'completed project excluded');
assert.equal(w.DesignLabs.contrast('#000000','#ffffff'),21);assert.equal(w.DesignLabs.contrast('#ffffff','#ffffff'),1);assert.equal(w.DesignLabs.grid(210,18,6,3),54);assert.equal(w.DesignLabs.grid(210,110,6,3),null);assert.equal(w.DesignLabs.grid(210,18,6,2.5),null);
await w.Pages.grafik(mount,{view:'labs'});mount.querySelector('[data-lab-note]').value='A three-column grid fits the editorial comparison.';mount.querySelector('[data-save-lab]').click();await w.Pages.grafik(mount,{view:'labs'});assert.match(mount.querySelector('[data-lab-note]').value,/three-column/);assert.equal(JSON.stringify(w.Store.load().stats),before);console.log('PASS: 130 topics, 88 substantive articles and all practice links; 16 complete briefs; five-stage completion; no false scores; contrast, grid and saved experiments');dom.window.close();})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
