const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const base=path.resolve(__dirname,'..'),dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'http://localhost/',runScripts:'outside-only'}),w=dom.window;
w.matchMedia=()=>({matches:false});w.scrollTo=()=>{};
for(const tag of w.document.querySelectorAll('script[src]')){const src=tag.getAttribute('src');if(!src.startsWith('assets/')||['assets/app.js','assets/auth.js'].includes(src))continue;w.eval(fs.readFileSync(path.join(base,src),'utf8'));if(src.endsWith('content-extra.js'))w.ContentExtras.apply();}
(async()=>{const mount=w.document.querySelector('#page-root'),before=JSON.stringify(w.Store.load().stats);assert.equal(w.LibraryReading.length,112);assert.equal(w.LibraryTopics.length,130);assert.equal(Object.keys(w.LibraryFoundations).length,24);let words=0;
for(const a of w.LibraryReading.filter(a=>!a.expanded)){assert.equal(a.sections.length,4);const text=a.sections.map(s=>s.text).join(' ');assert.ok(text.length>700,a.id+' substantive explanation');words+=text.split(/\s+/).length;}
for(const x of w.LibraryTopics){await w.Pages.bibliothek(mount,{subject:x[0],ref:x[1]});assert.ok(mount.querySelector('.library-reader'),x[1]);const body=mount.querySelector('[data-library-reading]');if(!w.LibraryExpansion.some(a=>a.id===x[1]))assert.equal(body.querySelectorAll('[data-library-foundation] .library-glossary dt').length,3);assert.ok(body.querySelector('[data-library-example]'));if(!w.LibraryExpansion.some(a=>a.id===x[1]))assert.ok(body.querySelector('.library-example-links a'));else assert.ok(mount.querySelector('[data-theory-practice]'));assert.ok(body.textContent.length>60,x[1]+' reading content');assert.equal(body.querySelectorAll('input,textarea,select,button,.exercise,form').length,0);assert.ok(!/[\u0400-\u04ff]/.test(body.textContent),x[1]+' no Russian');}
assert.equal(JSON.stringify(w.Store.load().stats),before);
await w.Pages.bibliothek(mount,{subject:'en',ref:'read-for-since'});assert.equal(mount.lang,'en');assert.ok(!/Aufgabe|Antwort|Merksatz/.test(mount.textContent));
await w.Pages.bibliothek(mount,{subject:'math',ref:'missing'});assert.ok(mount.textContent.includes('Artikel nicht gefunden'));
console.log(`PASS: 130 read-only articles, 24 original expanded readers (${words} words), source references, native languages and unchanged exercise progress`);dom.window.close();})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close();});
